name: Entorno Integracion Continua
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_to_master:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci
      - name: Run Eslinter
        run: npm run lint
      - name: Run Test
        run: npm test
      - name: Run Build
        run: npm run build
      # - name: Config Delivery in Heroku
        